RUNPATH("0:/ia_init.ks").
STAGE.
LOCK met TO TIME:SECONDS - ms.
WAIT 3.0.
STAGE.

WAIT 2.0.
LOCK tP TO 90 - ((90 - fP) * (met - 5) / (70 - 5)).
LOCK STEERING TO HEADING(90, tP).
UNTIL tP <= fP {
 WAIT 2.
}
LOCK STEERING TO HEADING(90, fP).
WAIT 15.
LOCK STEERING TO SHIP:PROGRADE.

WAIT UNTIL SHIP:ALTITUDE > 100000.
UNLOCK STEERING.
STAGE.
WAIT 1.
STAGE.
WAIT UNTIL STAGE:READY.
STAGE.
WAIT 48.
STAGE.
WAIT 2.
STAGE.
WAIT 50.
