LOCK f TO SHIP:FACING:VECTOR.
LOCK rR TO SHIP:FACING * R(0, 90, 0).
LOCK rt TO rR:VECTOR.
LOCK t TO VCRS(f, r).
LOCK cP TO 90 - VANG(SHIP:UP:VECTOR, SHIP:FACING:FOREVECTOR).
SET eP TO 55.

LOCK THROTTLE TO 1.0.
LOCK STEERING TO UP.
